Between Universe: Space Class Reference
Space Class Reference
The Space is the "world" class, it manage all physical object. It draw and update all objects it have and make the collisions tests. Also it move forward at each update.
#include <space.h>
Public Member Functions
Space ()
Space (QImage background, float viewX, float viewWidth, float viewHeight, float xEnd, float velocity=1)
Space.
~Space ()
void addObject (SpaceObject *object)
void addBlockedObject (SpaceObject *object)
The blocked object can't go out the viewport.
void paint (QPainter &context) const
void animate ()
void resizeHandler (float windowWidth, float windowHeight)
rescale the draw viewport to have the correct ratio
QRectF viewBound () const
bool isEnded () const
void applyTransform (QPainter &context, float windowWidth, float windowHeight)
scale and translate the context to suit the viewport
Static Public Attributes
static const QPen noPen = QPen(QColor(0,0,0,0))
static const QBrush noBrush = QBrush(QColor(0,0,0,0))
static const QPointF origin = QPointF(0,0)
Detailed Description
The Space is the "world" class, it manage all physical object. It draw and update all objects it have and make the collisions tests. Also it move forward at each update.
Constructor & Destructor Documentation
Space() [1/2]
Space::Space ()
Space() [2/2]
Space::Space (QImage background, float viewX, float viewWidth, float viewHeight, float xEnd, float velocity = 1)
Space.
Parameters
background
viewX initial x position
viewWidth viewport width
viewHeight viewport height
xEnd When viewport pass this value the level should be over
velocity the speed with which the viewport move
~Space()
Space::~Space ()
Member Function Documentation
addBlockedObject()
void Space::addBlockedObject (SpaceObject * object)
The blocked object can't go out the viewport.
addObject()
void Space::addObject (SpaceObject * object)
animate()
void Space::animate ()
References SpaceObject::animate(), SpaceObject::handleDeath(), SpaceObject::isDefinitelyDead(), SpaceObject::isInView(), and SpaceObject::setWorld().
applyTransform()
void Space::applyTransform (QPainter & context, float windowWidth, float windowHeight)
scale and translate the context to suit the viewport
References resizeHandler().
isEnded()
bool Space::isEnded () const
paint()
void Space::paint (QPainter & context) const
References SpaceObject::actualPosition(), SpaceObject::paint(), and SpaceObject::size().
resizeHandler()
void Space::resizeHandler (float windowWidth, float windowHeight)
rescale the draw viewport to have the correct ratio
viewBound()
QRectF Space::viewBound () const
Field Documentation
noBrush
const QBrush Space::noBrush = QBrush(QColor(0,0,0,0)) static
noPen
const QPen Space::noPen = QPen(QColor(0,0,0,0)) static
origin
const QPointF Space::origin = QPointF(0,0) static
The documentation for this class was generated from the following files:
include/space.h
src/space.cpp