Between Universe: ConfigDialog Class Reference
ConfigDialog Class Reference
Form used for editing the players and the game.
#include <configdialog.h>
Signals
void exitAsked ()
void accepted ()
void refused ()
Public Member Functions
ConfigDialog (QWidget *parent=0)
void clearPlayers ()
void addPlayer (Player *p, bool mandatory, bool enable)
void save ()
~ConfigDialog ()
void setLevelFile (QString file)
QString levelFile () const
Friends
class Game
Detailed Description
Form used for editing the players and the game.
Constructor & Destructor Documentation
ConfigDialog()
ConfigDialog::ConfigDialog (QWidget * parent = 0) explicit
~ConfigDialog()
ConfigDialog::~ConfigDialog ()
References accepted(), exitAsked(), and refused().
Member Function Documentation
accepted
void ConfigDialog::accepted () signal
addPlayer()
void ConfigDialog::addPlayer (Player * p, bool mandatory, bool enable)
clearPlayers()
void ConfigDialog::clearPlayers ()
exitAsked
void ConfigDialog::exitAsked () signal
levelFile()
QString ConfigDialog::levelFile () const
refused
void ConfigDialog::refused () signal
save()
void ConfigDialog::save ()
References PlayerWidget::save().
setLevelFile()
void ConfigDialog::setLevelFile (QString file)
Friends And Related Function Documentation
Game
friend class Game friend
The documentation for this class was generated from the following files:
include/configdialog.h
src/configdialog.cpp