Between Universe: Input Class Reference
Input Class Reference
This object is used as a key (like in a QMap), it define an hashcode from a QInputEvent It allow to seek an action triggered by a specific input.
#include <player.h>
Public Member Functions
Input ()
Input (const QInputEvent *e)
Input (const QInputEvent &e)
bool testInput (const Input &i2) const
virtual bool operator== (const Input &i2) const
virtual bool operator!= (const Input &i2) const
virtual bool operator< (const Input &i2) const
Input & operator= (Input i2)
long hashcode () const
void save (QSettings &settings, const QString &prefix)
Static Public Member Functions
static Input load (const QSettings &settings, const QString &prefix)
Detailed Description
This object is used as a key (like in a QMap), it define an hashcode from a QInputEvent It allow to seek an action triggered by a specific input.
Constructor & Destructor Documentation
Input() [1/3]
Input::Input ()
Input() [2/3]
Input::Input (const QInputEvent * e)
Input() [3/3]
Input::Input (const QInputEvent & e)
Member Function Documentation
hashcode()
long Input::hashcode () const
load()
Input Input::load (const QSettings & settings, const QString & prefix) static
operator!=()
bool Input::operator!= (const Input & i2) const virtual
operator<()
bool Input::operator< (const Input & i2) const virtual
operator=()
Input & Input::operator= (Input i2)
operator==()
bool Input::operator== (const Input & i2) const virtual
save()
void Input::save (QSettings & settings, const QString & prefix)
References SPECIAL_MASK, and TYPE_MASK.
testInput()
bool Input::testInput (const Input & i2) const inline
References hashcode(), load(), operator!=(), operator<(), operator=(), operator==(), and save().
The documentation for this class was generated from the following files:
include/player.h
src/player.cpp