Between Universe: Galata Class Reference
Galata Class Reference
This mode define a level of the Game.
#include <galata.h>
Public Slots
virtual bool update ()
bool updateStartTransition (float t)
bool updateEndTransition (float t)
Public Slots inherited from Mode
virtual bool update ()=0
update the game. May be used at each frame
virtual bool updateStartTransition (float t)=0
update the game at the start, when the mode is changing to this
virtual bool updateEndTransition (float t)=0
update the game at the end, when the mode is changing to another
Public Member Functions
Galata (Player *p1)
Galata (QFile &file, Player *p1)
void addPlayer (Player *p)
virtual bool inputHandle (QInputEvent *event)
Handle a input event.
QPointF initialShipPosition ()
void addShip (Ship *ship)
void addEnemy (Enemy *e)
void addItem (Item *i)
void handlePlayerDeath (Player *p)
void load (QFile &file)
void loadElement (const QDomElement &e)
PositionRange loadRange (const QDomElement &e)
Enemy * loadEnemy (const QDomElement &e)
Item * loadItem (const QDomElement &e)
Behavior * loadBehavior (const QDomElement &e)
void loadEnemySupplement (Enemy *enemy, const QDomElement &e)
const Space & space ()
~Galata ()
Public Member Functions inherited from Mode
Mode ()
const Renderer * renderer () const
Static Public Attributes
static QImage spaceBorder
Friends
class GalataRenderer
Additional Inherited Members
Protected Attributes inherited from Mode
Renderer * _renderer
Detailed Description
This mode define a level of the Game.
Constructor & Destructor Documentation
Galata() [1/2]
Galata::Galata (Player * p1)
References Mode::_renderer, addPlayer(), and GalataRenderer.
Galata() [2/2]
Galata::Galata (QFile & file, Player * p1)
References addPlayer(), and load().
~Galata()
Galata::~Galata ()
References Mode::_renderer.
Member Function Documentation
addEnemy()
void Galata::addEnemy (Enemy * e)
References Space::addObject().
addItem()
void Galata::addItem (Item * i)
References Space::addObject().
addPlayer()
void Galata::addPlayer (Player * p)
References Player::addShipToGalata(), and Player::setLevel().
addShip()
void Galata::addShip (Ship * ship)
References Space::addBlockedObject(), Space::addObject(), Ship::assert(), initialShipPosition(), SpaceObject::moveTo(), and Space::viewBound().
handlePlayerDeath()
void Galata::handlePlayerDeath (Player * p)
initialShipPosition()
QPointF Galata::initialShipPosition ()
inputHandle()
bool Galata::inputHandle (QInputEvent * event) virtual
Handle a input event.
Parameters
event QInputEvent which may be a QKeyEvent, QMouseEvent or QWheelEvent
Implements Mode.
References Player::inputHandle().
load()
void Galata::load (QFile & file)
References loadElement().
loadBehavior()
Behavior * Galata::loadBehavior (const QDomElement & e)
References B_String::addBehavior().
loadElement()
void Galata::loadElement (const QDomElement & e)
References addEnemy(), addItem(), loadEnemy(), loadEnemySupplement(), and loadItem().
loadEnemy()
Enemy * Galata::loadEnemy (const QDomElement & e)
References loadRange().
loadEnemySupplement()
void Galata::loadEnemySupplement (Enemy * enemy, const QDomElement & e)
References Enemy::addBehavior(), Enemy::addDroppedItems(), Player::color(), Player::life(), loadBehavior(), loadItem(), Player::name(), and Player::points().
loadItem()
Item * Galata::loadItem (const QDomElement & e)
References loadRange().
loadRange()
PositionRange Galata::loadRange (const QDomElement & e)
References Space::viewBound().
space()
const Space & Galata::space ()
update
bool Galata::update () virtual slot
References Space::animate(), and Space::isEnded().
updateEndTransition
bool Galata::updateEndTransition (float t) slot
updateStartTransition
bool Galata::updateStartTransition (float t) slot
Friends And Related Function Documentation
GalataRenderer
friend class GalataRenderer friend
Field Documentation
spaceBorder
QImage Galata::spaceBorder static
The documentation for this class was generated from the following files:
include/galata.h
src/galata.cpp