Between Universe: Enemy Class Reference
Enemy Class Reference
Enemy is a SpaceObject which can be destroyed by a ship It give points to the ship which destroyed it and can drop some Items It have some Behaviors which define its moves.
#include <enemy.h>
Public Member Functions
Enemy (int life, int damage, QSizeF _size, const PositionRange &range, int points=10)
~Enemy ()
bool isDead () const
bool isDefinitelyDead () const
bool isInView (float x1, float x2) const
void handleCollision (SpaceObject *o)
function called when the object met another
void handleDeath ()
function called when the object is removed from the Space due to its death
void animate ()
void addBehavior (Behavior *b)
void addDroppedItems (Item *i)
int points () const
void damageEnemy (Ship &ship, int damage)
Public Member Functions inherited from SpaceObject
SpaceObject (QSizeF _size)
void moveTo (const QPointF &p)
moveTo Ask to the Space to move at this position
bool updated ()
void setWorld (Space *world)
virtual void paint (QPainter &context) const =0
virtual ColliderObject * collider () const =0
QPointF actualPosition () const
QPointF requestedPosition () const
QSizeF size () const
Protected Attributes
int life
int damage
int _points
QPair< QPointF, QPointF > range
float deadState
QList< Behavior * > behaviors
QList< Item * > droppedItems
Protected Attributes inherited from SpaceObject
Space * world
QSizeF _size
Additional Inherited Members
Static Public Member Functions inherited from SpaceObject
static void drawExplosion (QPainter &context, float radius, float state)
Detailed Description
Enemy is a SpaceObject which can be destroyed by a ship It give points to the ship which destroyed it and can drop some Items It have some Behaviors which define its moves.
Constructor & Destructor Documentation
Enemy()
Enemy::Enemy (int life, int damage, QSizeF _size, const PositionRange & range, int points = 10)
~Enemy()
Enemy::~Enemy ()
References behaviors.
Member Function Documentation
addBehavior()
void Enemy::addBehavior (Behavior * b)
References behaviors.
addDroppedItems()
void Enemy::addDroppedItems (Item * i)
References droppedItems.
animate()
void Enemy::animate () virtual
Implements SpaceObject.
Reimplemented in CircleEnemy, and SquareEnemy.
References SpaceObject::actualPosition(), behaviors, and SpaceObject::moveTo().
damageEnemy()
void Enemy::damageEnemy (Ship & ship, int damage)
References Ship::addPoints(), damage, isDead(), life, and points().
handleCollision()
void Enemy::handleCollision (SpaceObject * o) virtual
function called when the object met another
Implements SpaceObject.
References damage, and Ship::damageShip().
handleDeath()
void Enemy::handleDeath () virtual
function called when the object is removed from the Space due to its death
Reimplemented from SpaceObject.
References SpaceObject::actualPosition(), Space::addObject(), droppedItems, SpaceObject::moveTo(), and SpaceObject::world.
isDead()
bool Enemy::isDead () const virtual
Returns
true if the object is dying and may be not used while the collisions tests
Implements SpaceObject.
References life.
isDefinitelyDead()
bool Enemy::isDefinitelyDead () const virtual
Returns
true if the object is definitely dead and should be removed from the Space
Reimplemented from SpaceObject.
isInView()
bool Enemy::isInView (float x1, float x2) const virtual
Parameters
x1 left border
x2 right border
Returns
true if the object should be in the space when the screen is at this position
Implements SpaceObject.
References range.
points()
int Enemy::points () const
References _points.
Field Documentation
_points
int Enemy::_points protected
behaviors
QList<Behavior*> Enemy::behaviors protected
damage
int Enemy::damage protected
deadState
float Enemy::deadState protected
droppedItems
QList<Item*> Enemy::droppedItems protected
life
int Enemy::life protected
range
QPair<QPointF, QPointF> Enemy::range protected
The documentation for this class was generated from the following files:
include/enemy.h
src/enemy.cpp