Between Universe: Player Class Reference
Player Class Reference
A Player is the user of the game, he has a name and a color. For a specific level, he has a ship and handle the event to control it.
#include <player.h>
Public Member Functions
Player ()
Player (QString _name, QColor _color, int _life, bool inGame=true)
void setShip (const Ship &shipModel)
void setMainWeapon (const Weapon &w)
void setSecondWeapon (const Weapon &w)
void setLevel (Galata *level)
void addShipToGalata ()
void handleShipDeath ()
void addControl (const Input &control, ShipAction shipAction)
void removeAction (ShipAction action)
virtual bool inputHandle (QInputEvent *event)
void addPoints (unsigned int _points)
void setName (const QString &name)
void setColor (const QColor &color)
void setLife (int life)
void putInGame (bool inGame)
bool canHandleInput (const Input &i) const
unsigned int points () const
QString name () const
QColor color () const
int life () const
bool isInGame () const
Data Fields
const Ship * shipModel
const Weapon * mainWeapon
const Weapon * secondWeapon
Detailed Description
A Player is the user of the game, he has a name and a color. For a specific level, he has a ship and handle the event to control it.
Constructor & Destructor Documentation
Player() [1/2]
Player::Player ()
Player() [2/2]
Player::Player (QString _name, QColor _color, int _life, bool inGame = true)
Member Function Documentation
addControl()
void Player::addControl (const Input & control, ShipAction shipAction)
addPoints()
void Player::addPoints (unsigned int _points)
References points().
addShipToGalata()
void Player::addShipToGalata ()
References Galata::addShip(), Ship::instanciate(), mainWeapon, secondWeapon, Ship::setMainWeapon(), Ship::setSecondWeapon(), and shipModel.
canHandleInput()
bool Player::canHandleInput (const Input & i) const
color()
QColor Player::color () const
handleShipDeath()
void Player::handleShipDeath ()
References addShipToGalata(), Galata::handlePlayerDeath(), and Ship::isDefinitelyDead().
inputHandle()
bool Player::inputHandle (QInputEvent * event) virtual
References Input::hashcode().
isInGame()
bool Player::isInGame () const
References SPECIAL_MASK, and TYPE_MASK.
life()
int Player::life () const
name()
QString Player::name () const
points()
unsigned int Player::points () const
putInGame()
void Player::putInGame (bool inGame)
removeAction()
void Player::removeAction (ShipAction action)
setColor()
void Player::setColor (const QColor & color)
References color().
setLevel()
void Player::setLevel (Galata * level)
setLife()
void Player::setLife (int life)
References life().
setMainWeapon()
void Player::setMainWeapon (const Weapon & w)
References mainWeapon, and Ship::setMainWeapon().
setName()
void Player::setName (const QString & name)
References name().
setSecondWeapon()
void Player::setSecondWeapon (const Weapon & w)
References secondWeapon, and Ship::setSecondWeapon().
setShip()
void Player::setShip (const Ship & shipModel)
References shipModel.
Field Documentation
mainWeapon
const Weapon* Player::mainWeapon
secondWeapon
const Weapon* Player::secondWeapon
shipModel
const Ship* Player::shipModel
The documentation for this class was generated from the following files:
include/player.h
src/player.cpp