Between Universe: Ship Class Reference
Ship Class Reference
The Ship is a specific SpaceObject that can destroy Enemy and be destroy by it This is the Player's object that allow his to play in a Galata.
#include <ship.h>
Public Member Functions
Ship (Player *parent, const QString &_name, const QImage &sprite, float acceleration, float _power, int life, int superModeDelay, float accelerateAmmount, float powerUpAmmount, Weapon *mainWeapon=NULL, Weapon *secondWeapon=NULL)
Ship (const QString &_name, const QImage &sprite, float acceleration, float _power, int life, int superModeDelay, float accelerateAmmount, float powerUpAmmount, Weapon *mainWeapon=NULL, Weapon *secondWeapon=NULL)
virtual void paint (QPainter &context) const
virtual void animate ()
virtual void handleDeath ()
function called when the object is removed from the Space due to its death
virtual ColliderObject * collider () const
void moveForward ()
void moveBackward ()
void moveUp ()
void moveDown ()
void stopForward ()
void stopBackward ()
void stopUp ()
void stopDown ()
void mainShootActivate ()
void secondShootActivate ()
void mainShootStop ()
void secondShootStop ()
void accelerate ()
void powerUp ()
void levelUp ()
void stopAccelerate ()
void stopPowerUp ()
void addBonus (Bonus *b)
void setMainWeapon (const Weapon &w)
void setSecondWeapon (const Weapon &w)
bool isDead () const
bool isDefinitelyDead () const
bool isInView (float x1, float x2) const
float power () const
QString name () const
void setParentPlayer (Player *parent)
void addPoints (int points)
void assert ()
assert, throw an exception if the ship isn't correctly set
virtual Ship * instanciate (Player *parent) const
void damageShip (Enemy &, int damage)
bool handleBulletCollision (SpaceObject *o, float damage)
void handleCollision (SpaceObject *o)
function called when the object met another
Public Member Functions inherited from SpaceObject
SpaceObject (QSizeF _size)
void moveTo (const QPointF &p)
moveTo Ask to the Space to move at this position
bool updated ()
void setWorld (Space *world)
QPointF actualPosition () const
QPointF requestedPosition () const
QSizeF size () const
Friends
void Bonus::addShipDefense (Ship &ship) const
void Bonus::removeShipDefense (Ship &ship) const
Additional Inherited Members
Static Public Member Functions inherited from SpaceObject
static void drawExplosion (QPainter &context, float radius, float state)
Protected Attributes inherited from SpaceObject
Space * world
QSizeF _size
Detailed Description
The Ship is a specific SpaceObject that can destroy Enemy and be destroy by it This is the Player's object that allow his to play in a Galata.
Constructor & Destructor Documentation
Ship() [1/2]
Ship::Ship (Player * parent, const QString & _name, const QImage & sprite, float acceleration, float _power, int life, int superModeDelay, float accelerateAmmount, float powerUpAmmount, Weapon * mainWeapon = NULL, Weapon * secondWeapon = NULL)
References SpaceObject::_size, Space::origin, setMainWeapon(), and setSecondWeapon().
Ship() [2/2]
Ship::Ship (const QString & _name, const QImage & sprite, float acceleration, float _power, int life, int superModeDelay, float accelerateAmmount, float powerUpAmmount, Weapon * mainWeapon = NULL, Weapon * secondWeapon = NULL)
Member Function Documentation
accelerate()
void Ship::accelerate ()
addBonus()
void Ship::addBonus (Bonus * b)
References Bonus::modifyShip().
addPoints()
void Ship::addPoints (int points)
References Player::addPoints().
animate()
void Ship::animate () virtual
Implements SpaceObject.
References Weapon::activated(), SpaceObject::actualPosition(), Bonus::animate(), isDead(), Bonus::isOver(), SpaceObject::moveTo(), Weapon::shoot(), stopAccelerate(), stopPowerUp(), Bonus::unmodifyShip(), and SpaceObject::world.
assert()
void Ship::assert ()
assert, throw an exception if the ship isn't correctly set
References Player::name().
collider()
ColliderObject * Ship::collider () const virtual
Returns
the collider which may be used for the collisions tests
Implements SpaceObject.
References SpaceObject::_size.
damageShip()
void Ship::damageShip (Enemy & , int damage)
handleBulletCollision()
bool Ship::handleBulletCollision (SpaceObject * o, float damage) virtual
Implements BulletCollisionListener.
References Enemy::damageEnemy().
handleCollision()
void Ship::handleCollision (SpaceObject * o) virtual
function called when the object met another
Implements SpaceObject.
References Enemy::damageEnemy().
handleDeath()
void Ship::handleDeath () virtual
function called when the object is removed from the Space due to its death
Reimplemented from SpaceObject.
References Player::handleShipDeath().
instanciate()
Ship * Ship::instanciate (Player * parent) const virtual
References Ship().
isDead()
bool Ship::isDead () const virtual
Returns
true if the object is dying and may be not used while the collisions tests
Implements SpaceObject.
isDefinitelyDead()
bool Ship::isDefinitelyDead () const virtual
Returns
true if the object is definitely dead and should be removed from the Space
Reimplemented from SpaceObject.
isInView()
bool Ship::isInView (float x1, float x2) const virtual
Parameters
x1 left border
x2 right border
Returns
true if the object should be in the space when the screen is at this position
Implements SpaceObject.
levelUp()
void Ship::levelUp ()
References Weapon::levelUp().
mainShootActivate()
void Ship::mainShootActivate ()
References Weapon::activate().
mainShootStop()
void Ship::mainShootStop ()
References Weapon::stop().
moveBackward()
void Ship::moveBackward ()
moveDown()
void Ship::moveDown ()
moveForward()
void Ship::moveForward ()
moveUp()
void Ship::moveUp ()
name()
QString Ship::name () const
paint()
void Ship::paint (QPainter & context) const virtual
Implements SpaceObject.
References SpaceObject::_size, SpaceObject::drawExplosion(), isDead(), Space::origin, and Bonus::paint().
power()
float Ship::power () const
powerUp()
void Ship::powerUp ()
secondShootActivate()
void Ship::secondShootActivate ()
References Weapon::activate().
secondShootStop()
void Ship::secondShootStop ()
References Weapon::stop().
setMainWeapon()
void Ship::setMainWeapon (const Weapon & w)
References SpaceObject::_size, and Weapon::instanciate().
setParentPlayer()
void Ship::setParentPlayer (Player * parent)
setSecondWeapon()
void Ship::setSecondWeapon (const Weapon & w)
References SpaceObject::_size, and Weapon::instanciate().
stopAccelerate()
void Ship::stopAccelerate ()
References superModeWaitDelay.
stopBackward()
void Ship::stopBackward ()
stopDown()
void Ship::stopDown ()
stopForward()
void Ship::stopForward ()
stopPowerUp()
void Ship::stopPowerUp ()
References superModeWaitDelay.
stopUp()
void Ship::stopUp ()
Friends And Related Function Documentation
Bonus::addShipDefense
void Bonus::addShipDefense (Ship & ship) const friend
Bonus::removeShipDefense
void Bonus::removeShipDefense (Ship & ship) const friend
The documentation for this class was generated from the following files:
include/ship.h
src/ship.cpp