Between Universe: WaveBullet Class Reference
WaveBullet Class Reference
#include <weapon.h>
Public Member Functions
WaveBullet (BulletCollisionListener &parent, float damage, int life, float width, float initialHeight, float vx, float vy, float heightInc)
WaveBullet (BulletCollisionListener &parent, float damage, int life, float width, float initialHeight, float vx, float vy, float heightInc, QPointF position)
bool isInView (float x1, float x2) const
virtual void paint (QPainter &context) const
ColliderObject * collider () const
void animate ()
void handleCollision (SpaceObject *o)
function called when the object met another
Public Member Functions inherited from Bullet
Bullet (BulletCollisionListener &parent, int life, QSizeF _size)
bool isDead () const
Public Member Functions inherited from SpaceObject
SpaceObject (QSizeF _size)
void moveTo (const QPointF &p)
moveTo Ask to the Space to move at this position
bool updated ()
void setWorld (Space *world)
virtual bool isDefinitelyDead () const
virtual void handleDeath ()
function called when the object is removed from the Space due to its death
QPointF actualPosition () const
QPointF requestedPosition () const
QSizeF size () const
Additional Inherited Members
Static Public Member Functions inherited from SpaceObject
static void drawExplosion (QPainter &context, float radius, float state)
Protected Attributes inherited from Bullet
int life
float damage
BulletCollisionListener & parent
Protected Attributes inherited from SpaceObject
Space * world
QSizeF _size
Constructor & Destructor Documentation
WaveBullet() [1/2]
WaveBullet::WaveBullet (BulletCollisionListener & parent, float damage, int life, float width, float initialHeight, float vx, float vy, float heightInc)
References Bullet::damage.
WaveBullet() [2/2]
WaveBullet::WaveBullet (BulletCollisionListener & parent, float damage, int life, float width, float initialHeight, float vx, float vy, float heightInc, QPointF position)
References SpaceObject::moveTo().
Member Function Documentation
animate()
void WaveBullet::animate () virtual
Reimplemented from Bullet.
References SpaceObject::_size, SpaceObject::actualPosition(), Bullet::animate(), and SpaceObject::moveTo().
collider()
ColliderObject * WaveBullet::collider () const virtual
Returns
the collider which may be used for the collisions tests
Implements SpaceObject.
handleCollision()
void WaveBullet::handleCollision (SpaceObject * o) virtual
function called when the object met another
Implements SpaceObject.
References Bullet::damage, BulletCollisionListener::handleBulletCollision(), and Bullet::life.
isInView()
bool WaveBullet::isInView (float x1, float x2) const virtual
Parameters
x1 left border
x2 right border
Returns
true if the object should be in the space when the screen is at this position
Implements SpaceObject.
References SpaceObject::actualPosition().
paint()
void WaveBullet::paint (QPainter & context) const virtual
Implements SpaceObject.
The documentation for this class was generated from the following files:
include/weapon.h
src/weapon.cpp