Between Universe: Game Class Reference
Game Class Reference
The main class, it manage the whole program by switching between the different mode Unfortunately, for the moment it manage only the Galata mode It has the common elements of the program as the characters, the ships, the weapons...
#include <game.h>
Public Slots
void setConfig ()
slot triggered after the configDialog close
Signals
void modeHasChanged ()
signal emitted when the mode as changed (when we should change the current renderer)
Public Member Functions
Game ()
void reload ()
reload a galata level from the current setting
void addDefaultPlayer (bool enabled)
add a new player from the default model
bool setDefaultInputToPlayer (Player *p)
Add to the player the differents control from the default input.
bool inputIsUsed (const Input &i) const
void setCurrentMode (Mode *current)
bool updateGame ()
void showConfigDialog ()
const Renderer * currentRenderer ()
Static Public Member Functions
static void staticInit ()
init all the common element
static QStringList shipNames ()
static QStringList weaponNames ()
static Ship * shipModelFromName (QString name)
static Weapon * weaponModelFromName (QString name)
Protected Member Functions
bool eventFilter (QObject *, QEvent *event)
Detailed Description
The main class, it manage the whole program by switching between the different mode Unfortunately, for the moment it manage only the Galata mode It has the common elements of the program as the characters, the ships, the weapons...
Constructor & Destructor Documentation
Game()
Game::Game ()
References addDefaultPlayer(), setConfig(), and staticInit().
Member Function Documentation
addDefaultPlayer()
void Game::addDefaultPlayer (bool enabled)
add a new player from the default model
Parameters
true if the player will be present in the next reload
References Player::color(), Player::life(), Player::name(), setDefaultInputToPlayer(), Player::setMainWeapon(), and Player::setShip().
currentRenderer()
const Renderer * Game::currentRenderer ()
References Mode::renderer().
eventFilter()
bool Game::eventFilter (QObject * , QEvent * event) protected
References Mode::inputHandle(), and showConfigDialog().
inputIsUsed()
bool Game::inputIsUsed (const Input & i) const
Returns
true if the Input is already reserved by the program or by a player
References Player::canHandleInput().
modeHasChanged
void Game::modeHasChanged () signal
signal emitted when the mode as changed (when we should change the current renderer)
reload()
void Game::reload ()
reload a galata level from the current setting
References Galata::addPlayer(), and modeHasChanged().
setConfig
void Game::setConfig () slot
slot triggered after the configDialog close
References ConfigDialog::levelFile(), reload(), and ConfigDialog::save().
setCurrentMode()
void Game::setCurrentMode (Mode * current)
References modeHasChanged().
setDefaultInputToPlayer()
bool Game::setDefaultInputToPlayer (Player * p)
Add to the player the differents control from the default input.
Returns
true if the default inputs have correctly been set
References Player::addControl(), and inputIsUsed().
shipModelFromName()
Ship * Game::shipModelFromName (QString name) static
shipNames()
QStringList Game::shipNames () static
showConfigDialog()
void Game::showConfigDialog ()
References ConfigDialog::addPlayer(), ConfigDialog::clearPlayers(), and ConfigDialog::setLevelFile().
staticInit()
void Game::staticInit () static
init all the common element
References ShipActions::mainWeaponActivate(), ShipActions::mainWeaponStop(), ShipActions::moveBackward(), ShipActions::moveDown(), ShipActions::moveForward(), ShipActions::moveUp(), ShipActions::stopBackward(), ShipActions::stopDown(), ShipActions::stopForward(), and ShipActions::stopUp().
updateGame()
bool Game::updateGame ()
References modeHasChanged(), Mode::update(), Mode::updateEndTransition(), and Mode::updateStartTransition().
weaponModelFromName()
Weapon * Game::weaponModelFromName (QString name) static
weaponNames()
QStringList Game::weaponNames () static
The documentation for this class was generated from the following files:
include/game.h
src/game.cpp