Between Universe: CircleEnemy Class Reference
CircleEnemy Class Reference
#include <enemy.h>
Public Member Functions
CircleEnemy (int life, int damage, const float radius, QColor c, bool fill, const PositionRange &range)
CircleEnemy (int life, int damage, const float radius, QColor c, bool fill, const PositionRange &range, const QPointF &position)
CircleEnemy (int life, int damage, const float radius, QImage sprite, const PositionRange &range)
CircleEnemy (int life, int damage, const float radius, QImage sprite, const PositionRange &range, const QPointF &position)
void paint (QPainter &context) const
ColliderObject * collider () const
void animate ()
Public Member Functions inherited from Enemy
Enemy (int life, int damage, QSizeF _size, const PositionRange &range, int points=10)
~Enemy ()
bool isDead () const
bool isDefinitelyDead () const
bool isInView (float x1, float x2) const
void handleCollision (SpaceObject *o)
function called when the object met another
void handleDeath ()
function called when the object is removed from the Space due to its death
void addBehavior (Behavior *b)
void addDroppedItems (Item *i)
int points () const
void damageEnemy (Ship &ship, int damage)
Public Member Functions inherited from SpaceObject
SpaceObject (QSizeF _size)
void moveTo (const QPointF &p)
moveTo Ask to the Space to move at this position
bool updated ()
void setWorld (Space *world)
QPointF actualPosition () const
QPointF requestedPosition () const
QSizeF size () const
Data Fields
QColor color
bool fill
QImage sprite
Additional Inherited Members
Static Public Member Functions inherited from SpaceObject
static void drawExplosion (QPainter &context, float radius, float state)
Protected Attributes inherited from Enemy
int life
int damage
int _points
QPair< QPointF, QPointF > range
float deadState
QList< Behavior * > behaviors
QList< Item * > droppedItems
Protected Attributes inherited from SpaceObject
Space * world
QSizeF _size
Constructor & Destructor Documentation
CircleEnemy() [1/4]
CircleEnemy::CircleEnemy (int life, int damage, const float radius, QColor c, bool fill, const PositionRange & range)
CircleEnemy() [2/4]
CircleEnemy::CircleEnemy (int life, int damage, const float radius, QColor c, bool fill, const PositionRange & range, const QPointF & position)
References SpaceObject::moveTo().
CircleEnemy() [3/4]
CircleEnemy::CircleEnemy (int life, int damage, const float radius, QImage sprite, const PositionRange & range)
CircleEnemy() [4/4]
CircleEnemy::CircleEnemy (int life, int damage, const float radius, QImage sprite, const PositionRange & range, const QPointF & position)
References SpaceObject::moveTo().
Member Function Documentation
animate()
void CircleEnemy::animate () virtual
Reimplemented from Enemy.
References Enemy::animate(), Enemy::deadState, and Enemy::isDead().
collider()
ColliderObject * CircleEnemy::collider () const virtual
Returns
the collider which may be used for the collisions tests
Implements SpaceObject.
References Space::origin.
paint()
void CircleEnemy::paint (QPainter & context) const virtual
Implements SpaceObject.
References color, Enemy::deadState, SpaceObject::drawExplosion(), fill, Enemy::isDead(), Space::noBrush, Space::origin, and sprite.
Field Documentation
color
QColor CircleEnemy::color
fill
bool CircleEnemy::fill
sprite
QImage CircleEnemy::sprite
The documentation for this class was generated from the following files:
include/enemy.h
src/enemy.cpp