Between Universe: MainWindow Class Reference
MainWindow Class Reference
#include <mainwindow.h>
Public Slots
void updateGame ()
void updateRenderer ()
Public Member Functions
MainWindow (QPoint position, QSize size, QWidget *parent=0)
MainWindow (QWidget *parent=0)
~MainWindow ()
Constructor & Destructor Documentation
MainWindow() [1/2]
MainWindow::MainWindow (QPoint position, QSize size, QWidget * parent = 0) explicit
MainWindow() [2/2]
MainWindow::MainWindow (QWidget * parent = 0) explicit
References Game::currentRenderer(), updateGame(), and updateRenderer().
~MainWindow()
MainWindow::~MainWindow ()
Member Function Documentation
updateGame
void MainWindow::updateGame () slot
References Game::updateGame().
updateRenderer
void MainWindow::updateRenderer () slot
References Game::currentRenderer(), and GLWidget::renderer.
The documentation for this class was generated from the following files:
include/mainwindow.h
src/mainwindow.cpp