Between Universe: DefenseBonus Class Reference
DefenseBonus Class Reference
#include <item.h>
Public Member Functions
DefenseBonus (Ship &ship, int delay)
virtual void modifyShip () const
virtual void unmodifyShip () const
virtual void paint (QPainter &context) const
draw something more in the ship
virtual void handleCollision ()
define what's happen if the ship has been hurt
Public Member Functions inherited from Bonus
Bonus (Ship &ship, int delay)
void addShipDefense (Ship &ship) const
void removeShipDefense (Ship &ship) const
bool isOver () const
virtual void animate ()
Additional Inherited Members
Protected Attributes inherited from Bonus
int delay
Ship & ship
Constructor & Destructor Documentation
DefenseBonus()
DefenseBonus::DefenseBonus (Ship & ship, int delay)
Member Function Documentation
handleCollision()
void DefenseBonus::handleCollision () virtual
define what's happen if the ship has been hurt
Implements Bonus.
References Bonus::delay.
modifyShip()
void DefenseBonus::modifyShip () const virtual
Implements Bonus.
References Bonus::addShipDefense(), and Bonus::ship.
paint()
void DefenseBonus::paint (QPainter & context) const virtual
draw something more in the ship
Implements Bonus.
References Bonus::ship, and SpaceObject::size().
unmodifyShip()
void DefenseBonus::unmodifyShip () const virtual
Implements Bonus.
References Bonus::removeShipDefense(), and Bonus::ship.
The documentation for this class was generated from the following files:
include/item.h
src/item.cpp