Between Universe: ColliderPolygon Class Reference
ColliderPolygon Class Reference
#include <colliderobject.h>
Public Member Functions
ColliderPolygon (float radius, QPointF center)
ColliderPolygon (float radius, QPointF center, const QList< QPointF > &points)
void addPoint (QPointF point)
bool collisionWithObject (const ColliderObject &object) const
bool collisionWithPoint (const QPointF &A) const
int collisionWithSegment (const QPointF &A, const QPointF &B) const
void translate (float tx, float ty)
const QList< QPointF > & points () const
Public Member Functions inherited from ColliderObject
ColliderObject (ColliderType type, float radius, const QPointF &center)
ColliderObject.
virtual bool isNearTo (const ColliderObject &object) const
ColliderObject * lightTranslate (float tx, float ty) const
void translate (const QPointF &t)
ColliderObject * lightTranslate (const QPointF &t) const
QPointF center () const
float radius () const
ColliderType type () const
Additional Inherited Members
Protected Types inherited from ColliderObject
enum ColliderType {
Circle, Rect, Line, Wall,
Ray, Polygone, NbColliderType
}
This enum allow an object to know how to proceed the collision test with an another.
Constructor & Destructor Documentation
ColliderPolygon() [1/2]
ColliderPolygon::ColliderPolygon (float radius, QPointF center)
ColliderPolygon() [2/2]
ColliderPolygon::ColliderPolygon (float radius, QPointF center, const QList< QPointF > & points)
References points().
Member Function Documentation
addPoint()
void ColliderPolygon::addPoint (QPointF point)
collisionWithObject()
bool ColliderPolygon::collisionWithObject (const ColliderObject & object) const virtual
Implements ColliderObject.
References collisionWithSegment(), ColliderObject::Line, and ColliderObject::type().
collisionWithPoint()
bool ColliderPolygon::collisionWithPoint (const QPointF & A) const virtual
Implements ColliderObject.
References pointOnTheRightOf(), and points().
collisionWithSegment()
int ColliderPolygon::collisionWithSegment (const QPointF & A, const QPointF & B) const virtual
Implements ColliderObject.
References intersectionBetweenSegment().
points()
const QList< QPointF > & ColliderPolygon::points () const
translate()
void ColliderPolygon::translate (float tx, float ty) virtual
Reimplemented from ColliderObject.
The documentation for this class was generated from the following files:
include/colliderobject.h
src/colliderobject.cpp