Between Universe: PlayerWidget Class Reference
PlayerWidget Class Reference
Form used for editing a player.
#include <configdialog.h>
Public Slots
void setAllEnabled (int state)
void updateColor ()
Public Member Functions
PlayerWidget (Player *p, bool enabled, bool mandatory)
~PlayerWidget ()
void save ()
Detailed Description
Form used for editing a player.
Constructor & Destructor Documentation
PlayerWidget()
PlayerWidget::PlayerWidget (Player * p, bool enabled, bool mandatory)
References Player::color(), Player::life(), Player::mainWeapon, Player::name(), Weapon::name(), Ship::name(), setAllEnabled(), Player::shipModel, Game::shipNames(), updateColor(), and Game::weaponNames().
~PlayerWidget()
PlayerWidget::~PlayerWidget ()
Member Function Documentation
save()
void PlayerWidget::save ()
References Player::putInGame(), Player::setColor(), Player::setLife(), Player::setMainWeapon(), Player::setName(), Player::setShip(), Game::shipModelFromName(), and Game::weaponModelFromName().
setAllEnabled
void PlayerWidget::setAllEnabled (int state) slot
updateColor
void PlayerWidget::updateColor () slot
The documentation for this class was generated from the following files:
include/configdialog.h
src/configdialog.cpp