Between Universe: ShipActions Namespace Reference
ShipActions Namespace Reference
Functions
void moveForward (Ship &)
void moveBackward (Ship &)
void moveUp (Ship &)
void moveDown (Ship &)
void stopForward (Ship &)
void stopBackward (Ship &)
void stopUp (Ship &)
void stopDown (Ship &)
void mainWeaponActivate (Ship &)
void secondWeaponActivate (Ship &)
void mainWeaponStop (Ship &)
void secondWeaponStop (Ship &)
void accelerate (Ship &)
void powerUp (Ship &)
Detailed Description
group all the actions that a Ship can handle
Function Documentation
accelerate()
void ShipActions::accelerate (Ship & ship)
References Ship::accelerate().
mainWeaponActivate()
void ShipActions::mainWeaponActivate (Ship & ship)
References Ship::mainShootActivate().
mainWeaponStop()
void ShipActions::mainWeaponStop (Ship & ship)
References Ship::mainShootStop().
moveBackward()
void ShipActions::moveBackward (Ship & ship)
References Ship::moveBackward().
moveDown()
void ShipActions::moveDown (Ship & ship)
References Ship::moveDown().
moveForward()
void ShipActions::moveForward (Ship & ship)
References Ship::moveForward().
moveUp()
void ShipActions::moveUp (Ship & ship)
References Ship::moveUp().
powerUp()
void ShipActions::powerUp (Ship & ship)
References Ship::powerUp().
secondWeaponActivate()
void ShipActions::secondWeaponActivate (Ship & ship)
References Ship::secondShootActivate().
secondWeaponStop()
void ShipActions::secondWeaponStop (Ship & ship)
References Ship::secondShootStop().
stopBackward()
void ShipActions::stopBackward (Ship & ship)
References Ship::stopBackward().
stopDown()
void ShipActions::stopDown (Ship & ship)
References Ship::stopDown().
stopForward()
void ShipActions::stopForward (Ship & ship)
References Ship::stopForward().
stopUp()
void ShipActions::stopUp (Ship & ship)
References Ship::stopUp().